### PR TITLE
feat (add-pagination) 

### PR DESCRIPTION
**Pull request by ShashankAG25**
[Issue #20](https://github.com/rahulharpal1603/CF-TopHacker/issues/20) : Added pagination to user listing, per page limit 100.

Screenshot from 2024-10-26 18-11-58
Screenshot from 2024-10-26 18-12-18
Screenshot from 2024-10-26 18-12-29
Screenshot from 2024-10-26 18-12-39

### CODE REVIEW

**Comment by rahulharpal1603** [comment]
Hi @ShashankAG25, Thank you for the PR! I have some suggestions before we can merge this. Please don't re-fetch all the contest data just to display the whole page. It will cause unnecessary overheads, and we want our extension to be fast and snappy. I would recommend making changes so that we need to fetch only once.

**Comment by rahulharpal1603** [comment]
> Hi @ShashankAG25, Thank you for the PR! I have some suggestions before we can merge this. Please don't re-fetch all the contest data just to display the next page. It will cause unnecessary overheads, and we want our extension to be fast and snappy. I would recommend making changes so that we need to fetch only once.

Also, the last row, which displays total hacks, should be the overall totals, just like the codeforces standing page. Regardless of what page we are on, the last row should always display the overall total.

**Comment by ShashankAG25** [comment]
Hi @rahulharpal1603 ,

Thank you for your feedback! I appreciate your suggestions. I have made the necessary changes to ensure that we fetch the contest data only once, which should improve the performance of the extension. Also made changes to the Total hacks data . Looking forward to your review!

**Comment by rahulharpal1603** [comment]
Thank you @ShashankAG25 !

**Review by rahulharpal1603 — COMMENTED** [review]
LGTM

**Pull request merged**
